apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-bootstrap
  namespace: {{ .Release.Namespace }}
data:
  bootstrap_node.sh: |
      #!/bin/bash
      set -x
      FILE=/app/.env
      cp /tmp/secrets/.env $FILE
      if [ -f "$FILE" ]; then
          echo "File $FILE exists."
          echo "Running Node.js app..."
          node /app/index.js
      else
          echo "File $FILE does not exist. Exiting."
          exit 1
      fi