apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.app.name }}-env
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .env: {{ .Values.secrets.env_file }}
  template:
    metadata:
      name: {{ .Values.app.name }}-env
      namespace: {{ .Release.Namespace }}
