apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-nginx.sh: |
        #!/bin/bash
        set -x

        FILE=/app/config.lua
        cp /tmp/secrets/config.lua $FILE
        lapis migrate
        echo "==========================="

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pg-backup-{{ .Release.Namespace }}
#   namespace: {{ .Values.targetNS }} kubectl get configmap opsapi-pg-backup-test -n test -o yaml
data:
    backup-database.sh: |
      #!/bin/bash
      set -x
      TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
      BACKUP_FILE="backup_$TIMESTAMP.sql.gz"

      pg_dump -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DATABASE" -F c | gzip > "/tmp/$BACKUP_FILE"

      # Install MinIO Client
      curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
      chmod +x mc && mv mc /usr/local/bin/

      # Configure MinIO and upload backup
      mc alias set myminio "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
      mc cp "/tmp/$BACKUP_FILE" myminio/"$MINIO_BUCKET"/"$BACKUP_FILE"

      # Cleanup
      rm -f "/tmp/$BACKUP_FILE"
