apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "stat -c %a /tmp && ls -la /tmp && cp /tmp/configmap/bootstrap-nginx.sh /usr/local/bin/bootstrap-nginx.sh && chmod +x /usr/local/bin/bootstrap-nginx.sh && /bin/sh /usr/local/bin/bootstrap-nginx.sh"]
          volumeMounts:
            - name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}-vol
              mountPath: /tmp/configmap
            - name: {{ .Release.Name }}-vol-{{ .Release.Namespace }}
              mountPath: /tmp/secrets
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 120
            periodSeconds: 30
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-secrets
          env:
            - name: LAPIS_ENVIRONMENT
              value: "production"
            - name: PROJECT_CODE
              value: {{ .Values.projectCode | default "tax_copilot" | quote }}
      volumes:
        - name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}-vol
          configMap:
            name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}
        - name: {{ .Release.Name }}-vol-{{ .Release.Namespace }}
          secret:
            secretName: "{{ .Release.Name }}-secrets"
            items:
            - key: LAPIS_CONFIG_LUA_FILE
              path: config.lua
