{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: "10m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        LAPIS_CONFIG_LUA_FILE: |
          local config = require("lapis.config")
          config("production", {
            port = 80,
            server = "nginx",
            code_cache = "on",
            num_workers = "1",
            session_name = "opsapi_session",
            secret = "{{`{{ .JWT_SECRET_KEY }}`}}",
            postgres = {
              host = "{{ .Values.database.host | default "{{`{{ .DB_HOST }}`}}" }}",
              user = "{{`{{ .DB_USER }}`}}",
              password = "{{`{{ .DB_PASSWORD }}`}}",
              database = "opsapi",
              port = {{`{{ .DB_PORT }}`}},
              ssl = false
            },
            google = {
              client_id = "{{`{{ .GOOGLE_CLIENT_ID }}`}}",
              client_secret = "{{`{{ .GOOGLE_CLIENT_SECRET }}`}}",
              redirect_uri = "{{`{{ .GOOGLE_REDIRECT_URI }}`}}"
            }
          })
  dataFrom:
  - extract:
      key: secret/opsapi/config
  - extract:
      key: secret/opsapi/login
  - extract:
      key: secret/{{ .Values.env }}/opsapi/backend
{{- end }}
