#!/usr/bin/env node
/**
 * Generate TypeScript types from an OpsAPI OpenAPI spec (URL or file).
 *
 *   node scripts/generate.mjs <url|file> [-o out.ts] [--core | --plugin <code>]
 *
 * --core drops plugin routes (operations marked x-opsapi-plugin) and the
 * schemas only they use: what this package ships as its main types.
 * --plugin <code> keeps ONLY that plugin's operations and the schemas they use:
 * the types behind a plugin sub-export (e.g. @opsapi/client/property-deals).
 * To type YOUR deployment, plugins included, run openapi-typescript on its
 * /openapi.json (README).
 */
import { readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';

const args = process.argv.slice(2);
const core = args.includes('--core');
const outIdx = args.indexOf('-o');
const out = outIdx >= 0 ? args[outIdx + 1] : null;
const pluginIdx = args.indexOf('--plugin');
const plugin = pluginIdx >= 0 ? args[pluginIdx + 1] : null;
const source = args.find((a, i) => !a.startsWith('-') && i !== outIdx + 1 && i !== pluginIdx + 1);
if (!source || (core && plugin) || (pluginIdx >= 0 && !plugin)) {
  console.error('usage: generate.mjs <url|file> [-o out.ts] [--core | --plugin <code>]');
  process.exit(1);
}

const spec = /^https?:\/\//.test(source)
  ? await (await fetch(source)).json()
  : JSON.parse(await readFile(source, 'utf8'));

if (core || plugin) {
  // --core: drop every plugin operation. --plugin: keep only that plugin's.
  const drop = (op) => (core ? Boolean(op['x-opsapi-plugin']) : op['x-opsapi-plugin'] !== plugin);
  for (const [path, item] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(item)) {
      if (op && typeof op === 'object' && drop(op)) delete item[method];
    }
    if (Object.keys(item).length === 0) delete spec.paths[path];
  }
  if (plugin && Object.keys(spec.paths).length === 0) {
    console.error(`no operations for plugin '${plugin}' in this spec (is it installed and enabled?)`);
    process.exit(1);
  }
  // Keep only schemas still reachable from the remaining paths.
  const schemas = spec.components?.schemas ?? {};
  const keep = new Set();
  const walk = (node) => {
    if (!node || typeof node !== 'object') return;
    if (typeof node.$ref === 'string') {
      const name = node.$ref.replace('#/components/schemas/', '');
      if (!keep.has(name) && schemas[name]) {
        keep.add(name);
        walk(schemas[name]);
      }
    }
    for (const v of Object.values(node)) walk(v);
  };
  walk(spec.paths);
  for (const name of Object.keys(schemas)) if (!keep.has(name)) delete schemas[name];
  spec.tags = (spec.tags ?? []).filter((t) =>
    Object.values(spec.paths).some((item) => Object.values(item).some((op) => op?.tags?.includes(t.name))));
}

const ast = await openapiTS(spec, { alphabetize: true });
const banner = `/**\n * OpsAPI ${core ? 'core ' : plugin ? `${plugin} plugin ` : ''}API types — generated by scripts/generate.mjs from ${
  /^https?:/.test(source) ? 'a live /openapi.json' : 'an OpenAPI file'
}. Do not edit.\n */\n`;
// The spec lists the common query parameters (page, per_page, search, …), not
// every filter an endpoint accepts (cursor, status, days, …): allow other keys
// too, while the listed ones keep their types.
const code = banner + astToString(ast)
  .replace(/query\?: never;/g, 'query?: { [key: string]: unknown };')
  .replace(/query\?: \{\n/g, (m) => `${m}[key: string]: unknown;\n`);
if (out) {
  await writeFile(out, code);
  console.error(`wrote ${out} (${Object.keys(spec.paths).length} paths)`);
} else {
  process.stdout.write(code);
}
