image:
  repository: bwalia/opsapi
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: lapis-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
