version: '3'

services:
  openresty:
    container_name: opsapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./lua:/usr/local/openresty/nginx/lua
      - ./lua.conf:/usr/local/openresty/nginx/conf/lua.conf
      - ./database/migrations:/opt/nginx/data/migrations
    networks:
      opsapi-network:

  postgres:
    container_name: opsapi-postgres-dev-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: opsapi
    networks:
      opsapi-network:
        ipv4_address: 172.19.0.10

  mariadb:
    container_name: opsapi-dev-db
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: msroot
      MYSQL_DATABASE: opsapi
      MYSQL_USER: msuser
      MYSQL_PASSWORD: mspassword
    networks:
      opsapi-network:
        ipv4_address: 172.19.0.11

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 7777:8080
    networks:
      opsapi-network:

networks:
  opsapi-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
