apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: opsapi-secrets
  namespace: default
spec:
  encryptedData:
    KEYCLOAK_AUTH_URL: AgBSa2R...
    KEYCLOAK_TOKEN_URL: AgBCdFE...
    KEYCLOAK_USERINFO_URL: AgBRWW...
    KEYCLOAK_CLIENT_ID: AgBSR2V...
    KEYCLOAK_CLIENT_SECRET: AgBBL...
    KEYCLOAK_REDIRECT_URI: AgBDnV...
    DB_HOST: AgBRt32...
    DB_USER: AgRRvf...
    DB_PASSWORD: AgBlSx...
    DATABASE: AgSdfU...
