app:
  env: CICD_ENV_REF_PLACEHOLDER
  name: opsapi-node
  image:
    repository: bwalia/opsapi-node
    tag: latest
    pullPolicy: Always
# imagePullSecrets: []
# nameOverride: ""
# fullnameOverride: ""

replicaCount: 1

secrets:
  env_file: helmfilesecretsplaceholder

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: CICD_NAMESPACE_PLACEHOLDER-opsapi-node.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: 3000

resources: {}
