---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opsapi-secrets
  namespace: default
spec:
  encryptedData:
    DATABASE: {{ .Values.app_secrets.database }}
    DB_HOST: {{ .Values.app_secrets.db_host }}
    DB_PASSWORD: {{ .Values.app_secrets.db_password }}
    DB_PORT: {{ .Values.app_secrets.db_port }}
    DB_USER: {{ .Values.app_secrets.db_user }}
    KEYCLOAK_AUTH_URL: {{ .Values.app_secrets.keycloak_auth_url }}
    KEYCLOAK_CLIENT_ID: {{ .Values.app_secrets.keycloak_client_id }}
    KEYCLOAK_CLIENT_SECRET: {{ .Values.app_secrets.keycloak_client_secret }}
    KEYCLOAK_REDIRECT_URI: {{ .Values.app_secrets.keycloak_redirect_uri }}
    KEYCLOAK_TOKEN_URL: {{ .Values.app_secrets.keycloak_token_url }}
    KEYCLOAK_USERINFO_URL: {{ .Values.app_secrets.keycloak_userinfo_url }}
  template:
    metadata:
      creationTimestamp: null
      name: opsapi-secrets
      namespace: default