---
apiVersion: v1
kind: Service
metadata:
  name: opsapi-nodeport
spec:
  selector:
    app: opsapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.svcAccessPort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: opsapi-svc
spec:
  selector:
    app: opsapi
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
