-- helpdesk_tickets: tenant-scoped rows behind /tickets (generated by `opsapi make:resource`).
-- Runs once, inside a transaction. Never edit it after it has been applied —
-- add a new migration file instead.
return function(schema, db)
    db.query([[
        CREATE TABLE IF NOT EXISTS helpdesk_tickets (
            id BIGSERIAL PRIMARY KEY,
            uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
            namespace_id INTEGER NOT NULL REFERENCES namespaces(id) ON DELETE CASCADE,
            title VARCHAR(255) NOT NULL,
            description TEXT,
            status VARCHAR(255) NOT NULL,
            priority INTEGER,
            requester_email VARCHAR(255),
            due_on DATE,
            resolved BOOLEAN,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    ]])
    db.query("CREATE INDEX IF NOT EXISTS idx_helpdesk_tickets_namespace ON helpdesk_tickets (namespace_id, id DESC)")
end
