apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      volumes:
        - name: env-file
          secret:
            secretName: {{ .Values.app.name }}-env
        - name: bootstrap
          configMap:
            name: {{ .Values.app.name }}-bootstrap
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp /tmp/configmap/bootstrap_node.sh /usr/local/bin/bootstrap_node.sh && chmod +x /usr/local/bin/bootstrap_node.sh && sh /usr/local/bin/bootstrap_node.sh"]          
          volumeMounts:
            - name: env-file
              mountPath: /tmp/secrets                
            - name: bootstrap
              mountPath: /tmp/configmap
