/**
 * Property Deals (OpsAPI plugin) — typed client for the dashboard pages.
 *
 * Shapes come from the plugin's OpenAPI (types/property-deals.generated.ts, generated by
 * @opsapi/client's generator — `npm run sync:property-deals-types`). Requests go through the
 * dashboard's apiClient, so auth, the workspace headers, token refresh and the offline queue
 * all apply. Contract: docs/property-deals/API.md.
 */
import { AxiosError } from 'axios';
import apiClient, { buildQueryString } from '@/lib/api-client';
import type { components } from '@/types/property-deals.generated';

type S = components['schemas'];

export type Me = S['PropertyDealsMe'];

// Renovations + due list (api/renovations.lua). Hand-written until the next
// `scripts/generate.mjs` run adds PropertyDealsRenovation / PropertyDealsDueItem.
export interface Renovation {
  uuid: string;
  project_uuid: string;
  board_uuid?: string | null;
  deal_uuid?: string | null;
  deal_name?: string | null;
  property_uuid?: string | null;
  address?: string | null;
  postcode?: string | null;
  template_key: string;
  name: string;
  status: string;
  budget?: number | string | null;
  budget_spent?: number | string | null;
  budget_currency?: string | null;
  start_date?: string | null;
  due_date?: string | null;
  jobs_total: number;
  jobs_done: number;
  jobs_overdue: number;
  created_at: string;
  builders_added?: string[];
}
export interface RenovationCreate {
  deal_uuid?: string;
  property_uuid?: string;
  name?: string;
  budget?: number;
  start_date?: string;
  target_end_date?: string;
  builder_user_uuids?: string[];
}
export interface DueItem {
  kind: 'deal_task' | 'renovation_job';
  uuid: string;
  title: string;
  due_at: string;
  overdue: boolean;
  status: string;
  deal_uuid?: string | null;
  deal_name?: string | null;
  project_uuid?: string | null;
  project_name?: string | null;
  column_name?: string | null;
  assignee?: string | null;
}
// Lead news + replies (api/signals.lua). Hand-written until the next generate run.
export type SignalKind = 'company_formed' | 'officer_appointed' | 'company_filing' | 'charge_registered' | 'social_post' | 'website' | 'news' | 'note';
export interface LeadSignal {
  uuid: string;
  lead_uuid: string;
  kind: SignalKind;
  source: 'companies_house' | 'manual' | 'share';
  title: string;
  summary?: string | null;
  url?: string | null;
  occurred_at: string;
  used_at?: string | null;
  created_at: string;
}
export type ReplyChannel = 'email' | 'sms' | 'whatsapp' | 'phone' | 'social' | 'other';
export interface LeadReply {
  uuid: string;
  lead_uuid: string;
  channel: ReplyChannel;
  from_address?: string | null;
  from_name?: string | null;
  subject?: string | null;
  received_at: string;
  body_text?: string | null;
  reply_temperature?: 'hot' | 'warm' | 'cold' | null;
  reply_score?: number | null;
  reply_reason?: string | null;
  hot_task_uuid?: string | null;
  matched_by?: string | null;
  alerted?: number;
  scored_by?: 'ai' | 'rules';
}
export interface HotLead {
  lead_uuid: string;
  first_name?: string | null;
  last_name?: string | null;
  company_name?: string | null;
  phone?: string | null;
  email?: string | null;
  owner_user_uuid?: string | null;
  lead_kind?: string | null;
  hot_score?: number | null;
  hot_reason?: string | null;
  last_reply_at?: string | null;
  call_task_uuid?: string | null;
  call_due_at?: string | null;
}
export interface ChOfficer {
  officer_id: string;
  name: string;
  appointments?: number;
  address?: string;
  born?: string;
}
export interface DueList {
  days: number;
  everyone: boolean;
  items: DueItem[];
}

export type Today = S['PropertyDealsToday'];
export type Deal = S['PropertyDealsDeal'];
export type DealCreate = S['PropertyDealsDealCreate'];
export type DealBoard = S['PropertyDealsDealBoard'];
export type DealOverview = S['PropertyDealsDealOverview'];
export type DealHealth = S['PropertyDealsDealHealth'];
export type Gate = S['PropertyDealsGate'];
export type Task = S['PropertyDealsTask'];
export type TaskSummary = S['PropertyDealsTaskSummary'];
export type UrgencyFactor = S['PropertyDealsUrgencyFactor'];
export type Lead = S['PropertyDealsLead'];
export type LeadDetailsUpdate = S['PropertyDealsLeadDetailsUpdate'];
export type Property = S['PropertyDealsProperty'];
export type BuyerProfile = S['PropertyDealsBuyerProfile'];
export type Supplier = S['PropertyDealsSupplier'];
export type SupplierWrite = S['PropertyDealsSupplierWrite'];
export type Booking = S['PropertyDealsBooking'];
export type Enquiry = S['PropertyDealsEnquiry'];
export type Chase = S['PropertyDealsChase'];
export type ComplianceCheck = S['PropertyDealsComplianceCheck'];
export type Document = S['PropertyDealsDocument'];
export type Approval = S['PropertyDealsApproval'];
export type ApprovalDecision = S['PropertyDealsApprovalDecision'];
export type WorkflowTemplate = S['PropertyDealsWorkflowTemplate'];
export type WorkflowTemplateVersion = S['PropertyDealsWorkflowTemplateVersion'];
export type MapResult = S['PropertyDealsMapResult'];
export type MapFeature = S['PropertyDealsMapFeature'];
export type PropertyCard = S['PropertyDealsPropertyCard'];
export type Digest = S['PropertyDealsDigest'];
export type TimelineItem = S['PropertyDealsTimelineItem'];
export type MatchWithBreakdown = S['PropertyDealsMatchWithBreakdown'];
export type AgentRun = S['PropertyDealsAgentRun'];
export type Agent = S['PropertyDealsAgent'];
export type AgentConfig = S['PropertyDealsAgentConfig'];
export type AiRoute = S['PropertyDealsAiRoute'];
export type Connector = S['PropertyDealsConnector'];
export type MailConnector = S['PropertyDealsMailConnector'];
export type NotificationPreferences = S['PropertyDealsNotificationPreferences'];
export type SavedSearch = S['PropertyDealsSavedSearch'];
export type ScoutAlert = S['PropertyDealsScoutAlert'];
export type CompanyCheck = S['PropertyDealsCompanyCheck'];

/** Core workspace AI provider (/api/v2/namespace/ai-providers). Keys never come back. */
export interface AiProvider {
  uuid: string;
  name: string;
  provider_type: 'anthropic' | 'openai' | 'gemini' | 'azure_openai' | 'mistral' | 'openai_compatible' | 'ollama' | 'jobshout';
  base_url?: string;
  default_model?: string;
  models?: string[];
  has_secret: boolean;
  secret_hint?: string;
  username?: string;
  options?: Record<string, unknown>;
  is_local?: boolean;
  enabled?: boolean;
  input_cost_per_mtok?: number;
  output_cost_per_mtok?: number;
  last_tested_at?: string;
  last_error?: string;
}

export interface PluginSettingDef {
  name: string;
  label: string;
  type: string;
  default?: unknown;
  description?: string;
  enum?: string[];
  min?: number;
  max?: number;
  required?: boolean;
  secret?: boolean;
  /** The workspace's current value (secrets: never returned, see is_set). */
  value?: unknown;
  is_set?: boolean;
}

export interface Envelope<T> {
  success: boolean;
  data: T;
  meta?: { page?: number; per_page?: number; total?: number; total_pages?: number; [k: string]: unknown };
}

export interface PdError {
  status: number;
  message: string;
  details?: unknown;
  code?: string;
}

const BASE = '/api/v2/property-deals';
const JSON_HDR = { headers: { 'Content-Type': 'application/json' } };

/** Turn any request error into { status, message, details } for toasts and inline errors. */
export function pdError(e: unknown): PdError {
  if (e instanceof AxiosError) {
    const body = (e.response?.data ?? {}) as { error?: unknown; message?: string; details?: unknown; code?: string };
    const err = body.error;
    const message =
      typeof err === 'string'
        ? err
        : (err as { message?: string } | undefined)?.message || body.message || e.message;
    return { status: e.response?.status ?? 0, message, details: body.details, code: body.code };
  }
  return { status: 0, message: e instanceof Error ? e.message : String(e) };
}

/** A readable one-liner, including field errors (details: { field: message } or a list). */
export function pdErrorText(e: unknown): string {
  const err = pdError(e);
  const d = err.details;
  if (d && typeof d === 'object' && !Array.isArray(d)) {
    const parts = Object.entries(d as Record<string, unknown>)
      .filter(([, v]) => typeof v === 'string')
      .map(([k, v]) => `${k}: ${v}`);
    if (parts.length) return `${err.message} — ${parts.join('; ')}`;
  }
  if (Array.isArray(d) && d.length && typeof d[0] === 'string') return `${err.message} — ${d.slice(0, 3).join('; ')}`;
  return err.message;
}

function qs(params?: Record<string, unknown>): string {
  if (!params) return '';
  const clean: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(params)) if (v !== undefined && v !== null && v !== '') clean[k] = v;
  const q = buildQueryString(clean);
  return q ? (q.startsWith('?') ? q : `?${q}`) : '';
}

async function get<T>(path: string, params?: Record<string, unknown>): Promise<Envelope<T>> {
  return (await apiClient.get<Envelope<T>>(BASE + path + qs(params))).data;
}
async function send<T>(method: 'post' | 'put' | 'delete', path: string, body?: unknown): Promise<Envelope<T>> {
  if (method === 'delete') return (await apiClient.delete<Envelope<T>>(BASE + path)).data;
  return (await apiClient[method]<Envelope<T>>(BASE + path, body ?? {}, JSON_HDR)).data;
}
async function core<T>(method: 'get' | 'post' | 'put' | 'delete', path: string, body?: unknown): Promise<Envelope<T>> {
  if (method === 'get' || method === 'delete') return (await apiClient[method]<Envelope<T>>(path)).data;
  return (await apiClient[method]<Envelope<T>>(path, body ?? {}, JSON_HDR)).data;
}

export type TaskUpdate = Partial<{
  pd_status: string;
  owner_user_uuid: string | null;
  snoozed_until: string | null;
  snooze_reason: string | null;
  evidence: Record<string, unknown>;
  priority: string;
}>;

export const pdService = {
  // Who / what
  me: () => get<Me>('/me'),
  setupState: () => get<unknown>('/setup'),
  setup: () => send<unknown>('post', '/setup'),
  today: (limit = 50) => get<Today>('/today', { limit }),
  leadSignals: (leadUuid: string) => get<LeadSignal[]>(`/leads/${leadUuid}/signals`),
  addLeadSignal: (leadUuid: string, body: { kind: SignalKind; text?: string; url?: string; title?: string }) =>
    send<LeadSignal>('post', `/leads/${leadUuid}/signals`, body),
  deleteSignal: (uuid: string) => send<{ deleted: boolean }>('delete', `/signals/${uuid}`),
  leadReplies: (leadUuid: string) => get<LeadReply[]>(`/leads/${leadUuid}/replies`),
  logLeadReply: (leadUuid: string, body: { channel: ReplyChannel; text: string; received_at?: string }) =>
    send<LeadReply>('post', `/leads/${leadUuid}/replies`, body),
  hotLeads: (mine = false) => get<HotLead[]>('/hot-leads', { mine: mine ? 'true' : undefined }),
  chOfficers: (q: string) => get<ChOfficer[]>('/companies-house/officers', { q }),
  runSignals: () => send<Record<string, unknown>>('post', '/signals/run'),
  followUp: (leadUuid: string, body: { channel?: 'email' | 'whatsapp' | 'sms'; signal_uuid?: string; note?: string }) =>
    send<{ task_uuid: string; run_uuid?: string; status: string }>('post', `/leads/${leadUuid}/follow-up`, body),
  due: (days = 7, mine = false) => get<DueList>('/due', { days, mine: mine ? 'true' : undefined }),
  renovations: (params?: { status?: 'active' | 'completed' | 'all'; deal_uuid?: string }) =>
    get<Renovation[]>('/renovations', params),
  createRenovation: (body: RenovationCreate) => send<Renovation>('post', '/renovations', body),
  digest: () => get<Digest>('/digest'),

  // Deals
  board: (template?: string) => get<DealBoard>('/deals/board', { template }),
  deals: (params?: Record<string, unknown>) => get<Deal[]>('/deals', params),
  deal: (id: string) => get<Deal>(`/deals/${id}`),
  createDeal: (body: DealCreate) => send<Deal>('post', '/deals', body),
  updateDeal: (id: string, body: Partial<Deal>) => send<Deal>('put', `/deals/${id}`, body),
  overview: (id: string) => get<DealOverview>(`/deals/${id}/overview`),
  timeline: (id: string, page = 1) => get<TimelineItem[]>(`/deals/${id}/timeline`, { page, per_page: 50 }),
  gate: (id: string, to?: string) => get<Gate>(`/deals/${id}/gate`, { to }),
  moveStage: (id: string, to: string) => send<{ deal: Deal; tasks_created: Task[] }>('post', `/deals/${id}/stage`, { to }),
  health: (id: string) => get<DealHealth>(`/deals/${id}/health`),
  parties: (dealUuid: string) => get<unknown[]>('/deal-parties', { deal_uuid: dealUuid, per_page: 100 }),
  addParty: (body: Record<string, unknown>) => send<unknown>('post', '/deal-parties', body),

  // Tasks
  tasks: (params?: Record<string, unknown>) => get<Task[]>('/tasks', params),
  task: (id: string) => get<Task>(`/tasks/${id}`),
  createTask: (body: Record<string, unknown>) => send<Task>('post', '/tasks', body),
  updateTask: (id: string, body: TaskUpdate) => send<Task>('put', `/tasks/${id}`, body),
  agentRun: (id: string, note?: string) => send<AgentRun>('post', `/tasks/${id}/agent-run`, note ? { note } : {}),
  run: (id: string) => get<AgentRun>(`/agent-runs/${id}`),
  cancelRun: (id: string) => send<AgentRun>('post', `/agent-runs/${id}/cancel`),
  contactLog: (id: string, body: Record<string, unknown>) => send<Chase>('post', `/tasks/${id}/contact-log`, body),

  // Legal
  enquiries: (dealUuid: string) => get<Enquiry[]>('/enquiries', { deal_uuid: dealUuid, per_page: 100, sort: 'raised_at' }),
  createEnquiry: (body: Record<string, unknown>) => send<Enquiry>('post', '/enquiries', body),
  updateEnquiry: (id: string, body: Record<string, unknown>) => send<Enquiry>('put', `/enquiries/${id}`, body),
  chases: (params: Record<string, unknown>) => get<Chase[]>('/chases', { per_page: 100, sort: 'sent_at', order: 'desc', ...params }),
  createChase: (body: Record<string, unknown>) => send<Chase>('post', '/chases', body),

  // Documents
  documents: (params: Record<string, unknown>) => get<Document[]>('/documents', params),
  document: (id: string) => get<Document>(`/documents/${id}`),
  uploadDocument: async (form: FormData) =>
    (await apiClient.post<Envelope<Document>>(`${BASE}/documents`, form, { headers: { 'Content-Type': 'multipart/form-data' } })).data,
  deleteDocument: (id: string) => send<unknown>('delete', `/documents/${id}`),

  // Compliance
  compliance: (params?: Record<string, unknown>) => get<ComplianceCheck[]>('/compliance-checks', params),
  createCheck: (body: Record<string, unknown>) => send<ComplianceCheck>('post', '/compliance-checks', body),
  updateCheck: (id: string, body: Record<string, unknown>) => send<ComplianceCheck>('put', `/compliance-checks/${id}`, body),

  // Approvals
  inbox: (all = false) => get<Approval[]>('/approvals/inbox', all ? { all: 'true' } : undefined),
  approvals: (params?: Record<string, unknown>) => get<Approval[]>('/approvals', params),
  decide: (id: string, body: ApprovalDecision) => send<Approval>('post', `/approvals/${id}/decide`, body),
  retryApproval: (id: string) => send<Approval>('post', `/approvals/${id}/retry`),
  requestApproval: (body: Record<string, unknown>) => send<Approval>('post', '/approvals', body),

  // Leads (Property Deals fields on CRM leads)
  lead: (uuid: string) => get<Lead>(`/leads/${uuid}`),
  leads: (params?: Record<string, unknown>) => get<Lead[]>('/leads', params),
  saveLeadDetails: (uuid: string, body: LeadDetailsUpdate) => send<Lead>('put', `/leads/${uuid}/details`, body),

  // Properties, map, matching
  properties: (params?: Record<string, unknown>) => get<Property[]>('/properties', params),
  property: (id: string) => get<Property>(`/properties/${id}`),
  createProperty: (body: Record<string, unknown>) => send<Property>('post', '/properties', body),
  updateProperty: (id: string, body: Record<string, unknown>) => send<Property>('put', `/properties/${id}`, body),
  enrich: (id: string) => send<unknown>('post', `/properties/${id}/enrich`),
  map: (params: Record<string, unknown>) => get<MapResult>('/map', params),
  card: (id: string) => get<PropertyCard>(`/properties/${id}/card`),
  propertyMatches: (id: string) => get<MatchWithBreakdown[]>(`/properties/${id}/matches`),
  buyerMatches: (id: string) => get<MatchWithBreakdown[]>(`/buyer-profiles/${id}/matches`),
  recomputeMatches: (body: Record<string, unknown>) => send<{ scored: number }>('post', '/matches/recompute', body),
  sendDealPack: (matchId: string) => send<Approval>('post', `/matches/${matchId}/send`, {}),
  updateMatch: (id: string, status: string) => send<unknown>('put', `/matches/${id}`, { status }),
  savedSearches: () => get<SavedSearch[]>('/saved-searches', { per_page: 100 }),
  saveSearch: (body: Record<string, unknown>) => send<SavedSearch>('post', '/saved-searches', body),
  deleteSearch: (id: string) => send<unknown>('delete', `/saved-searches/${id}`),
  runSearch: (id: string) => send<Record<string, number>>('post', `/saved-searches/${id}/run`),
  scoutAlerts: (params?: Record<string, unknown>) => get<ScoutAlert[]>('/scout-alerts', params),
  markAlertsSeen: (uuids?: string[]) => send<{ updated: number }>('post', '/scout-alerts/seen', uuids ? { uuids } : {}),

  // Buyers
  buyers: (params?: Record<string, unknown>) => get<BuyerProfile[]>('/buyer-profiles', params),
  buyerDirectory: (params?: Record<string, unknown>) => get<(BuyerProfile & { name?: string; email?: string })[]>('/buyer-profiles/directory', params),
  createBuyer: (body: Record<string, unknown>) => send<BuyerProfile>('post', '/buyer-profiles', body),
  updateBuyer: (id: string, body: Record<string, unknown>) => send<BuyerProfile>('put', `/buyer-profiles/${id}`, body),
  companySearch: (q: string) => get<{ company_number: string; title: string; company_status?: string }[]>('/companies/search', { q }),
  companyCheck: (id: string, company_number?: string) =>
    send<CompanyCheck>('post', `/buyer-profiles/${id}/company-check`, company_number ? { company_number } : {}),

  // Suppliers
  suppliers: (params?: Record<string, unknown>) => get<Supplier[]>('/suppliers', params),
  createSupplier: (body: SupplierWrite) => send<Supplier>('post', '/suppliers', body),
  updateSupplier: (id: string, body: SupplierWrite) => send<Supplier>('put', `/suppliers/${id}`, body),
  nearest: (body: Record<string, unknown>) => send<Record<string, unknown>[]>('post', '/suppliers/nearest', body),
  bookings: (params?: Record<string, unknown>) => get<Booking[]>('/bookings', params),
  confirmBooking: (id: string, body: Record<string, unknown>) => send<Approval>('post', `/bookings/${id}/confirm`, body),

  // Templates
  templates: () => get<WorkflowTemplate[]>('/workflow-templates'),
  template: (id: string) => get<WorkflowTemplate>(`/workflow-templates/${id}`),
  updateTemplate: (id: string, body: Record<string, unknown>) => send<WorkflowTemplate>('put', `/workflow-templates/${id}`, body),
  templateVersions: (id: string) => get<WorkflowTemplateVersion[]>(`/workflow-templates/${id}/versions`),
  publishVersion: (id: string, definition: unknown, notes?: string) =>
    send<WorkflowTemplateVersion>('post', `/workflow-templates/${id}/versions`, { definition, notes }),
  importTemplate: (definition: unknown) => send<WorkflowTemplate>('post', '/workflow-templates/import', { definition }),
  exportTemplate: (id: string) => get<unknown>(`/workflow-templates/${id}/export`),

  // AI
  agents: () => get<Agent[]>('/ai/agents'),
  saveAgent: (key: string, body: Partial<AgentConfig>) => send<AgentConfig>('put', `/ai/agents/${key}`, body),
  routes: () => get<AiRoute[]>('/ai/routes'),
  saveRoute: (jobType: string, body: Record<string, unknown>) => send<AiRoute>('put', `/ai/routes/${jobType}`, body),
  aiUsage: (days = 30) => get<Record<string, unknown>>('/ai/usage', { days }),
  aiProviders: () => core<AiProvider[]>('get', '/api/v2/namespace/ai-providers'),
  saveAiProvider: (body: Record<string, unknown>, uuid?: string) =>
    uuid ? core<AiProvider>('put', `/api/v2/namespace/ai-providers/${uuid}`, body) : core<AiProvider>('post', '/api/v2/namespace/ai-providers', body),
  deleteAiProvider: (uuid: string) => core<unknown>('delete', `/api/v2/namespace/ai-providers/${uuid}`),
  testAiProvider: (uuid: string) => core<Record<string, unknown>>('post', `/api/v2/namespace/ai-providers/${uuid}/test`),
  jobshoutAgents: (uuid: string) => core<{ id: string; name: string }[]>('get', `/api/v2/namespace/ai-providers/${uuid}/agents`),

  // Data + mail connectors
  connectors: () => get<Connector[]>('/connectors'),
  saveConnector: (body: Record<string, unknown>, uuid?: string) =>
    uuid ? send<Connector>('put', `/connectors/${uuid}`, body) : send<Connector>('post', '/connectors', body),
  deleteConnector: (uuid: string) => send<unknown>('delete', `/connectors/${uuid}`),
  runConnector: (uuid: string, postcode?: string) => send<{ fetched: number; stored: number }>('post', `/connectors/${uuid}/run`, { postcode }),
  mailConnectors: () => get<MailConnector[]>('/mail-connectors'),
  saveMailConnector: (body: Record<string, unknown>, uuid?: string) =>
    uuid ? send<MailConnector>('put', `/mail-connectors/${uuid}`, body) : send<MailConnector>('post', '/mail-connectors', body),
  deleteMailConnector: (uuid: string) => send<unknown>('delete', `/mail-connectors/${uuid}`),
  syncMailConnector: (uuid: string) => send<{ fetched: number; stored: number; matched: number }>('post', `/mail-connectors/${uuid}/sync`),

  // Me
  notificationPrefs: () => get<NotificationPreferences>('/notification-preferences'),
  saveNotificationPrefs: (body: Partial<NotificationPreferences> | Record<string, unknown>) =>
    send<NotificationPreferences>('put', '/notification-preferences', body),

  // Plugin settings (core /namespace/plugins)
  pluginInfo: async () => {
    const res = await core<Record<string, unknown>[]>('get', '/api/v2/namespace/plugins');
    return (res.data || []).find((p) => p.code === 'property_deals') as
      | { code: string; name: string; enabled: boolean; settings: PluginSettingDef[] }
      | undefined;
  },
  savePluginSettings: (settings: Record<string, unknown>) =>
    core<unknown>('put', '/api/v2/namespace/plugins/property_deals', { settings }),

  // Reports + engine
  report: (name: string, params?: Record<string, unknown>) => get<Record<string, unknown> | unknown[]>(`/reports/${name}`, params),
  exportUrl: (entity: string, format: 'csv' | 'json') => `${BASE}/export/${entity}?format=${format}`,
  exportFile: async (entity: string, format: 'csv' | 'json') =>
    (await apiClient.get<Blob>(`${BASE}/export/${entity}?format=${format}`, { responseType: 'blob' })).data,
  runEngine: (checks: string[]) => send<Record<string, unknown>>('post', '/engine/run', { checks }),
};

export default pdService;
