  #  alerting:
  #    discord:
  #      webhook_url: "YOUR_DISCORD_WEBHOOK"
  #      default_alert: 3
    endpoints:
      - name: "Lapis [Dev]"
        group: "Private Services"
        url: "http://172.71.0.12/health"
        interval: 30s
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 10000"
          - "len([BODY]) > 10"
      # - name: "Postgres [Dev]"
      #   group: "Prirvate Services"
      #   url: "http://opsapi-postgres-dev-db:5432/"
      #   interval: 30s
      #   conditions:
      #     - "[STATUS] == 200"
      #     - "[RESPONSE_TIME] < 1000"
      #     - "len([BODY]) > 10"