name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: whisky03

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decode and Export Kubeconfig
      env:
        KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_DATA_K3S3 }}
      run: |
        echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        echo "Kubeconfig decoded and exported successfully."

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Deploy Sealed Secret
      run: kubectl apply -f devops/kubernetes/sealed-secret.yaml

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install opsapi ./chart \
          --set image.repository=bwalia/opsapi \
          --set image.tag=latest \
          --namespace default --create-namespace
