-- Tickets: /api/v2/helpdesk/tickets  (generated by `opsapi make:resource`; edit freely)
--
--   GET    /tickets       list    ?page=&per_page=&q=&sort=&order=asc|desc&<filter>=
--   GET    /tickets/:id   show
--   POST   /tickets       create
--   PUT    /tickets/:id   update (only the fields sent)
--   DELETE /tickets/:id   delete
--
-- Every route needs a namespace (X-Namespace-Id header) and the permission
-- helpdesk_tickets.read|create|update|delete; rows are always scoped to the caller's
-- namespace. Add custom routes in this file or a new api/*.lua — see PLUGINS.md.
local sdk = require("helper.plugin-sdk")

return function(app)
    sdk.crud(app, "/tickets", {
        table = "helpdesk_tickets",
        module = "helpdesk_tickets",
        fields = {
            title = { type = "string", required = true },
            description = { type = "text" },
            status = { type = "string", required = true, enum = { "open", "pending", "closed" } },
            priority = { type = "integer", min = 1, max = 5 },
            requester_email = { type = "email", label = "Requester" },
            due_on = { type = "date", label = "Due" },
            resolved = { type = "boolean" },
        },
        searchable = { "title", "description", "status", "requester_email" },
        filterable = { "title", "status", "priority", "requester_email", "due_on", "resolved" },
        sortable = { "title", "status", "priority", "requester_email", "due_on", "resolved", "created_at", "updated_at" },
        -- Dashboard page (/dashboard/plugins/helpdesk/tickets): title, table columns, form order
        ui = {
            label = "Tickets",
            columns = { "title", "status", "priority", "requester_email", "due_on" },
            form = { "title", "status", "priority", "requester_email", "due_on", "resolved", "description" },
        },
    })
end
